## never composed an OAK query for environmental media (at least not yet)
#- filename: local/env-local-scale-candidate-non-leaf-mam-individual-exclusion-applied-ids.txt
#  output_prefix: non_host_oak_queries
#  header: false
#  data_column_number: 1
- filename: local/soil-ids.tsv
  output_prefix: all_soils_oak
  header: false
  data_column_number: 1
- filename: local/EnvMediumSoilEnum-pvs-keys-parsed-unique.csv
  output_prefix: historical_permissible_values
  header: true
  data_column_name: normalized_curie
- filename: local/nmdc-production-biosamples-soil-env_medium.tsv
  output_prefix: NMDC_soil
  header: false
  data_column_number: 1
  count_column_number: 2
- filename: local/ncbi-mims-soil-biosamples-env_medium-annotated.tsv
  output_prefix: NCBI_mims_soil_trusting_CURIe
  header: true
  data_column_name: normalized_curie
  count_column_name: count
- filename: local/ncbi-mims-soil-biosamples-env_medium-annotated.tsv
  output_prefix: NCBI_mims_soil_trusting_labels
  header: true
  data_column_name: matched_id
  count_column_name: count
- filename: local/goldData_biosamples-inferred-soil-env_medium-counts.tsv
  output_prefix: GOLD_env_terr_soil
  header: false
  data_column_number: 1
  count_column_number: 2
